resourcePack: "https://download1482.mediafire.com/0svvcwnt82tg/hs3bf31s4ycm815/NegativeSpaceFont4pre3.zip"
basicActionBarDuration: 60 # In ticks 20 ticks = 1 second
actionBarRefreshRate: 20 # In ticks 20 ticks = 1 second

customFontWidth:
  "\uF999": 0